version: '3.1'

services:

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: crud
    volumes:
      - ./:/app

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080