version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: crud
    volumes:
      - ./:/app

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080