version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: crud
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./cooperdata:/cooperdata
      - ./pgdata:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080